<?php
/**
 * Created by PhpStorm.
 * User: tarran
 * Date: 15/12/2016
 * Time: 12:50
 */

namespace Tarranjones\snap;


class Snap extends CardGame
{

    protected $pile;

    public function addPlayer(Player $player)
    {
        return parent::addPlayer($player); // TODO: Change the autogenerated stub
    }


    public function takeTurn($player){
        if($this->isSnap()){
            $player->takePile();
        }
    }


    public function isSnap(){

    }

    public function checkWinner(){

        if($this->getPlayerCount() === 1) {
            return $this->getPlayer(0);

        }

        if($this->isSnap()){
            return $this->getCurrentPlayer();
        }
        return false;
    }

}